#https://localhost:8086/

version: '3'
services:
    meshcentral:
        restart: always
        container_name: meshcentral
        image: typhonragewind/meshcentral:latest
        ports:
            - 8086:443  # Port pour accéder à l'interface Web de MeshCentral
        environment:
            - HOSTNAME=localhost  # Utilisation de localhost pour une installation locale
            - REVERSE_PROXY=false
            - IFRAME=false
            - ALLOW_NEW_ACCOUNTS=true
            - WEBRTC=false
            - BACKUPS_PW=MyAwesomePasswordPleaseChangeMe
            - BACKUP_INTERVAL=24
            - BACKUP_KEEP_DAYS=10
        volumes:
            - ./meshcentral/data:/opt/meshcentral/meshcentral-data
            - ./meshcentral/user_files:/opt/meshcentral/meshcentral-files
            - ./meshcentral/backups:/opt/meshcentral/meshcentral-backups
